In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
data = pd.read_excel('portatour-Kunden.xlsx')

In [4]:
data.head()

,Kundenname,Straße,Ort,PLZ,Land
0,138395 F & T Terrix Limitid,"Chichester Street, Unit 14 Chichester busines...",Rochdale,OL16 2AU,GB
1,Addagrip Surface,Bell Lane Industrial Estate,"Uckfield, East Sussex",TN22 1QL,GB
2,AHL Architectural Hardware,Boucher Place,BELFAST,BT12 6TA,GB
3,ALIVA UK,Arlington Business Park,"Theale, Berkshire",RG7 4TY,GB
4,ALIVA UK,"Oak Tree Barn, Unit 6",Warrington,WA4 4BX,GB

In [ ]:
API_KEY= "API_KEY_HERE"

In [14]:
from openai import OpenAI
import time

client = OpenAI(api_key=API_KEY)

def research_company(name, street, city, plz, country):
    """Use GPT-5.2 with web search to research a company."""
    prompt = (
        f"Company: '{name}', Address: {street}, {city}, {plz}, {country}.\n"
        f"Context: building materials / construction industry.\n\n"
        f"Answer VERY briefly — max 1 short bullet point per question, no full sentences:\n"
        f"TAETIGKEIT: Core business (max 5 words)\n"
        f"GROESSE: Size (employees/revenue/locations, max 5 words)\n"
        f"PRODUKTPALETTE: List only product categories (e.g. WDVS, Trockenbau, Putz, Fassade, Dämmstoffe). Just comma-separated keywords.\n\n"
        f"Format exactly as:\n"
        f"TAETIGKEIT: ...\n"
        f"GROESSE: ...\n"
        f"PRODUKTPALETTE: ..."
    )

    try:
        response = client.responses.create(
            model="gpt-5.2",
            tools=[{"type": "web_search"}],
            input=prompt,
        )
        return response.output_text
    except Exception as e:
        print(f"Error for {name}: {e}")
        return "TAETIGKEIT: N/A\nGROESSE: N/A\nPRODUKTPALETTE: N/A"

def parse_response(text):
    """Parse the structured response into 3 fields."""
    result = {"Tätigkeit": "", "Größe": "", "Produktpalette": ""}
    for line in text.split("\n"):
        line = line.strip()
        if line.upper().startswith("TAETIGKEIT:"):
            result["Tätigkeit"] = line.split(":", 1)[1].strip()
        elif line.upper().startswith("GROESSE:"):
            result["Größe"] = line.split(":", 1)[1].strip()
        elif line.upper().startswith("PRODUKTPALETTE:"):
            result["Produktpalette"] = line.split(":", 1)[1].strip()
    return result

In [15]:

# TEST: Run only on the first row
row = data.iloc[0]
print(f"Testing: {row['Kundenname']}")
raw = research_company(row["Kundenname"], row["Straße"], row["Ort"], row["PLZ"], row["Land"])
print("\n--- Raw Response ---")
print(raw)
print("\n--- Parsed ---")
parsed = parse_response(raw)
for k, v in parsed.items():
    print(f"{k}: {v}")

Testing: 138395 F & T Terrix Limitid

--- Raw Response ---
TAETIGKEIT: Fassaden-/Putzsysteme Hersteller/Anbieter
GROESSE: klein; <50 MA; 1 Standort
PRODUKTPALETTE: Putz, Render, Farbe, Sprayputz, Sprührender, Brick Slips, EWI/WDVS, Innenputz, Fassadensysteme

--- Parsed ---
Tätigkeit: Fassaden-/Putzsysteme Hersteller/Anbieter
Größe: klein; <50 MA; 1 Standort
Produktpalette: Putz, Render, Farbe, Sprayputz, Sprührender, Brick Slips, EWI/WDVS, Innenputz, Fassadensysteme

In [6]:
data = df_enriched.copy()  # to avoid modifying original

NameError: name 'df_enriched' is not defined

In [17]:
from concurrent.futures import ThreadPoolExecutor, as_completed

def process_row(idx, row):
    """Worker function for parallel execution."""
    raw = research_company(row["Kundenname"], row["Straße"], row["Ort"], row["PLZ"], row["Land"])
    parsed = parse_response(raw)
    return idx, row["Kundenname"], parsed

# Run enrichment in parallel with 5 workers
MAX_WORKERS = 20
results = {}
total = len(data)

with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
    futures = {
        executor.submit(process_row, idx, row): idx
        for idx, row in data.iterrows()
    }
    for future in as_completed(futures):
        idx, name, parsed = future.result()
        results[idx] = parsed
        print(f"[{len(results)}/{total}] {name} ✓")

# Build final dataframe with new columns (in original order)
#df_enriched = data.copy()
#df_enriched["Tätigkeit"] = [results[i]["Tätigkeit"] for i in range(total)]
#df_enriched["Größe"] = [results[i]["Größe"] for i in range(total)]
#df_enriched["Produktpalette"] = [results[i]["Produktpalette"] for i in range(total)]

#print(f"\nDone! {len(df_enriched)} companies enriched.")
#df_enriched

[1/180] Belgrade Insulations ✓
[2/180] Bradfords ✓
[3/180] Belmore Supplies ✓
[4/180] Belgrade Insulations ✓
[5/180] BTS INTERIORS LTD. ✓
[6/180] alsecco (U.K.) Ltd. ✓
[7/180] Addagrip Surface ✓
[8/180] AHL Architectural Hardware ✓
[9/180] Belgrade Insulations (138552) ✓
[10/180] British Gypsum PLC. ✓
[11/180] Amaroc -  gelöscht ✓
[12/180] Bryson Products ✓
[13/180] Bluebuild Energy ✓
[14/180] 138395 F & T Terrix Limitid ✓
[15/180] ALIVA UK ✓
[16/180] Bostik Ltd ✓
[17/180] Benchmark Building ✓
[18/180] Baumit  Ltd ✓
[19/180] Allmat (East Surrey) Ltd. ✓
[20/180] ALIVA UK ✓

:

:

In [ ]:
pd.read_excel('portatour-Kunden.xlsx').head()

In [12]:
df_enriched.head()

,Kundenname,Straße,Ort,PLZ,Land,Tätigkeit,Größe,Produktpalette
0,138395 F & T Terrix Limitid,"Chichester Street, Unit 14 Chichester busines...",Rochdale,OL16 2AU,GB,"Fassaden-/Putzsysteme, Baustoffe",klein; <50 MA; 1 Standort,"Render, Putz/Spritzputz, Farben/Lacksysteme, K..."
1,Addagrip Surface,Bell Lane Industrial Estate,"Uckfield, East Sussex",TN22 1QL,GB,Resin surfacing systems manufacturer,"<50 employees, 1 UK site","resin-bound surfacing, resin-bonded surfacing,..."
2,AHL Architectural Hardware,Boucher Place,BELFAST,BT12 6TA,GB,Architectural ironmongery supply,Single site; small business,"Schlösser, Zylinder, Schlüssel/Schließsysteme,..."
3,ALIVA UK,Arlington Business Park,"Theale, Berkshire",RG7 4TY,GB,"Fassadenlösungen, hinterlüftete Systeme","2 Standorte, KMU (<50)","ETICS/EWI, Rainscreen, Porzellan/Feinsteinzeug..."
4,ALIVA UK,"Oak Tree Barn, Unit 6",Warrington,WA4 4BX,GB,"Fassadensysteme, EWI, Rainscreen","HQ Süd, Büro/Showroom Nord","ETICS/EWI, Rainscreen-Cladding, Fassadenpaneel..."

In [13]:
df_enriched.to_excel("kunden_enriched.xlsx", index=False)

In [7]:
df_enriched=pd.read_excel("kunden_enriched.xlsx")

In [4]:
df_enriched.head()

,Kundenname,Straße,Ort,PLZ,Land,Tätigkeit,Größe,Produktpalette
0,138395 F & T Terrix Limitid,"Chichester Street, Unit 14 Chichester busines...",Rochdale,OL16 2AU,GB,"Fassaden-/Putzsysteme, Baustoffe",klein; <50 MA; 1 Standort,"Render, Putz/Spritzputz, Farben/Lacksysteme, K..."
1,Addagrip Surface,Bell Lane Industrial Estate,"Uckfield, East Sussex",TN22 1QL,GB,Resin surfacing systems manufacturer,"<50 employees, 1 UK site","resin-bound surfacing, resin-bonded surfacing,..."
2,AHL Architectural Hardware,Boucher Place,BELFAST,BT12 6TA,GB,Architectural ironmongery supply,Single site; small business,"Schlösser, Zylinder, Schlüssel/Schließsysteme,..."
3,ALIVA UK,Arlington Business Park,"Theale, Berkshire",RG7 4TY,GB,"Fassadenlösungen, hinterlüftete Systeme","2 Standorte, KMU (<50)","ETICS/EWI, Rainscreen, Porzellan/Feinsteinzeug..."
4,ALIVA UK,"Oak Tree Barn, Unit 6",Warrington,WA4 4BX,GB,"Fassadensysteme, EWI, Rainscreen","HQ Süd, Büro/Showroom Nord","ETICS/EWI, Rainscreen-Cladding, Fassadenpaneel..."

In [6]:
df_enriched.columns

Index(['Kundenname', 'Straße', 'Ort', 'PLZ', 'Land', 'Tätigkeit', 'Größe',
       'Produktpalette'],
      dtype='object')

In [10]:
from concurrent.futures import ThreadPoolExecutor, as_completed
from openai import OpenAI

client = OpenAI(api_key=API_KEY)

def fetch_website(name, street, city, plz, country):
    """Use GPT with web search to find the real company website."""
    prompt = (
        f"Find the official website URL for this company:\n"
        f"Company name: '{name}'\n"
        f"Address: {street}, {plz} {city}, {country}\n"
        f"Industry context: building materials / construction (Baustoffhandel, Baustoffe)\n\n"
        f"Rules:\n"
        f"- Return ONLY the base domain URL (e.g. https://www.example.com)\n"
        f"- It MUST be the real, verified website of this specific company\n"
        f"- Do NOT guess or invent URLs\n"
        f"- Do NOT return social media pages, directory listings, or third-party sites\n"
        f"- If you cannot find a verified website, return exactly: NICHT_GEFUNDEN\n\n"
        f"Answer with ONLY the URL or NICHT_GEFUNDEN, nothing else."
    )

    try:
        response = client.responses.create(
            model="gpt-5.2",
            tools=[{"type": "web_search"}],
            input=prompt,
        )
        url = response.output_text.strip()

        # Validate: must look like a real URL and not be the fallback
        if "NICHT_GEFUNDEN" in url.upper() or "nicht" in url.lower():
            return ""
        if not url.startswith("http"):
            # Sometimes the model returns domain without scheme
            if "." in url and " " not in url and len(url) < 100:
                url = "https://" + url
            else:
                return ""
        # Strip trailing slashes/whitespace and remove any surrounding quotes
        url = url.strip().strip('"').strip("'").rstrip("/")
        return url
    except Exception as e:
        print(f"Error for {name}: {e}")
        return ""


def process_website_row(idx, row):
    """Worker function for parallel website lookup."""
    url = fetch_website(row["Kundenname"], row["Straße"], row["Ort"], row["PLZ"], row["Land"])
    return idx, row["Kundenname"], url


# Run website lookup in parallel
MAX_WORKERS = 20
website_results = {}
total = len(df_enriched)

with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
    futures = {
        executor.submit(process_website_row, idx, row): idx
        for idx, row in df_enriched.iterrows()
    }
    for future in as_completed(futures):
        idx, name, url = future.result()
        website_results[idx] = url
        status = url if url else "(not found)"
        print(f"[{len(website_results)}/{total}] {name} → {status}")

# Add website column
df_enriched["Website"] = [website_results[i] for i in range(total)]

found = df_enriched["Website"].astype(bool).sum()
print(f"\nDone! Websites found: {found}/{total}")
df_enriched[["Kundenname", "Website"]].head(20)

[1/180] Baumit  Ltd → https://baumit.co.uk
[2/180] Belgrade Insulations → https://www.belgradeinsulations.com
[3/180] Bluebuild Energy → https://www.bluebuildenergy.com
[4/180] Belgrade Insulations → https://www.belgradeinsulations.com
[5/180] Bostik Ltd → https://www.bostik.com
[6/180] Addagrip Surface → https://addagrip.co.uk
[7/180] ALIVA UK → https://alivauk.com
[8/180] Bryson Products → https://www.bryson.co.uk
[9/180] Belmore Supplies → https://www.belmoretools.co.uk
[10/180] Bradfords → https://www.bradfords.co.uk
[11/180] Belgrade Insulations (138552) → https://www.belgradeinsulations.com
[12/180] alsecco (U.K.) Ltd. → https://alsecco.co.uk
[13/180] ALIVA UK → https://alivauk.com
[14/180] 138395 F & T Terrix Limitid → https://www.ft-terrix.com
[15/180] Amaroc -  gelöscht → (not found)
[16/180] British Gypsum PLC. → https://www.british-gypsum.com
[17/180] Allmat (East Surrey) Ltd. → https://www.allmat-buildingsupplies.co.uk
[18/180] CCF Ltd. → https://www.ccfltd.co.uk
[19/180] CCF Ltd. → https://www.ccfltd.co.uk
[20/180] Benchmark Building → (not found)
[21/180] CPI Mortars Ltd. → https://www.cpieuromix.com
[22/180] Clan Products Ltd. → https://www.clan.co.uk
[23/180] Direct Building Products ltd → https://directbuildingproducts.co.uk
[24/180] Charles Tennant Ltd. → https://ctni.co.uk
[25/180] Building Systems → (not found)
[26/180] Contract Beads Ltd. → https://www.contractbeads.co.uk
[27/180] BULLOCK BUILDBASE → https://www.huwsgray.co.uk
[28/180] Durham Render Centre Ltd. → https://durhamrendercentre.co.uk
[29/180] CEMCO Merchant Network Ltd. → (not found)
[30/180] CRT International Ltd. → https://crtinternational.co.uk
[31/180] Encon Insulation  Nevill Long Leeds (138550) → https://www.encon.co.uk
[32/180] Eco Facades LTD → https://ecofacadesltd.co.uk
[33/180] AHL Architectural Hardware → (not found)
[34/180] ENCON insulation Ltd. → https://www.encon.co.uk
[35/180] Enewall Systems Ltd. → (not found)
[36/180] Elliott Brothers Ltd. → https://elliotts.uk
[37/180] ETAG Fixings UK Limited → https://www.etagfixings.co.uk
[38/180] EWI STORE LTD → https://ewistore.co.uk
[39/180] Galaxy Insulation & Dry Lining Midlands → https://www.galaxyinsulation.co.uk
[40/180] FGF (Continental) Ltd. → https://www.fgflimited.co.uk
[41/180] CPD Distribution Plc → (not found)
[42/180] Galaxy Insulation & Dry Lining  → https://www.galaxyinsulation.co.uk
[43/180] FASSA UK LTD 138456 → https://www.fassabortolo.it
[44/180] Galaxy Insulation & Dry Lining East Midlands → https://www.galaxyinsulation.co.uk
[45/180] Expamet Building Products → https://www.expamet.co.uk
[46/180] GH Supplies London → https://www.ghsupplies.co.uk
[47/180] BTS INTERIORS LTD. → (not found)
[48/180] Erne Group → (not found)
[49/180] GO INTERIORS → https://gointeriors.co.uk
[50/180] CSS (North West) Limited → (not found)
[51/180] H. Butterfield Group → https://www.hbutterfield.co.uk
[52/180] Galaxy Insulation and Dry Lining → https://www.galaxyinsulation.co.uk
[53/180] Castle Timber & Building Mat. → (not found)
[54/180] Insulated Render Systems Scotland Ltd. → https://www.irsconstruction.co.uk
[55/180] IBB Builder's Merchant → https://www.ibb.uk
[56/180] Jewson Ltd. → https://www.jewson.co.uk
[57/180] HALDANE FISHER → https://www.haldane-fisher.com
[58/180] J.T. Atkinson → https://www.jtatkinson.co.uk
[59/180] JB Products → https://www.jbproducts.co.uk
[60/180] Insulation Shop Ltd → https://www.insulationshop.co
[61/180] JUB Systems UK Ltd → https://jubrenders.co.uk
[62/180] JUB Systems UK Ltd → https://www.jubrenders.co.uk
[63/180] Etex Building Performance Limited → https://www.siniat.co.uk
[64/180] K Systems → https://k.systems
[65/180] Jackson Building Centres → https://www.jacksonbc.co.uk
[66/180] KiIsaran International → (not found)
[67/180] Larsen Building Products → https://larsenbuildingproducts.com
[68/180] Harborne Building Supplies → (not found)
[69/180] Licata Building Systems Ltd (138482) → https://licataltd.co.uk
[70/180] Kilsaran International → https://www.kilsaran.ie
[71/180] Kilwaughter Chemical Co. Limited → https://www.kilwaughter.com
[72/180] Just Render Ltd. → https://www.justrender.co.uk
[73/180] Licata Building Systems Ltd. → https://licataltd.co.uk
[74/180] Knauf Insulation Ltd → https://www.knaufinsulation.co.uk
[75/180] Licata Building Systems Ltd. (138750) → https://licataltd.co.uk
[76/180] IH TOOLS → (not found)
[77/180] Killwaughter Ltd → (not found)
[78/180] Licata Building Systems Ltd. 138454 → https://licataltd.co.uk
[79/180] MAPEI (UK) Ltd. → https://www.mapei.co.uk
[80/180] Knauf  GmbH UK → https://www.knauf.co.uk
[81/180] MacNaughton Blair → https://www.macblair.com
[82/180] Mike Wye → https://mikewye.co.uk
[83/180] Minster Drywall → https://www.minsteronline.co.uk
[84/180] LOCUSRITE LIMITED → https://www.locusrite.co.uk
[85/180] Mould Growth Consultants Ltd. → https://www.mgcltd.co.uk
[86/180] Klimasan Limited → (not found)
[87/180] Keelsupply Ltd. → https://ndi.co.uk
[88/180] Mauer UK Ltd. → (not found)
[89/180] Monocouche Render Systems Ltd. (138473) → https://monocouche.co.uk
[90/180] Minster Drywall → https://www.minsteronline.co.uk
[91/180] NMBS National Merchant Buying → https://www.nmbs.co.uk
[92/180] MURDOCK GROUP → https://www.murdockbuildersmerchants.com
[93/180] NEVILL LONG → (not found)
[94/180] Marmorit UK → (not found)
[95/180] OBAS UK Limited → https://www.obas.com
[96/180] MAMUT-THERM UK LTD. → (not found)
[97/180] Lord & Downing → https://www.lordanddowning.co.uk
[98/180] P1 The Plasterers 1 Stop Shop → https://www.plasterers1stopshop.co.uk
[99/180] Natural Building → https://www.soprema.co.uk
[100/180] McArthur Group Ltd. → (not found)
[101/180] Nevill Long → https://www.nevilllong.co.uk
[102/180] NBG → https://www.nationalbuyinggroup.com
[103/180] O'Neill Wholesale → https://oneillsupplies.com
[104/180] Nevill Long → https://www.nevilllong.co.uk
[105/180] PERMAROCK PRODUCTS LIMITED → https://www.permarock.com
[106/180] NEVILL LONG → https://www.nevilllong.co.uk
[107/180] Nevill Long → https://www.encon.co.uk
[108/180] Nevill Long → https://www.encon.co.uk
[109/180] Profiles Store → https://profilestore.co.uk
[110/180] Nevill Long → https://encon.co.uk
[111/180] Principal Building Products Ltd → https://principalbuildingproducts.com
[112/180] Protektor Group UK Ltd. → https://protektor.co.uk
[113/180] Nevill Long Ltd. → (not found)
[114/180] PPG Architectural Coatings UK Ltd. → https://ppgac.co.uk
[115/180] PRB SYSTEMS LTD → https://www.prbsystems.co.uk
[116/180] PENLAW HOUSE → https://www.penlaw.co.uk
[117/180] Penlaw Fixings Ltd. → https://www.penlaw.co.uk
[118/180] REMIX DRY MORTAR Ltd → https://remixdrymortar.co.uk
[119/180] Penlaw House → https://www.penlaw.co.uk
[120/180] Quietstone UK Ltd. → https://www.quietstone.co.uk
[121/180] Probead Ltd. → https://probead.com
[122/180] RE-KKUR (NI) Ltd. → https://www.re-kkur.com
[123/180] Rendit Ltd. → https://www.rendit.co.uk
[124/180] Rockwool Ltd. → https://www.rockwool.com
[125/180] Rendmaster Ltd 138455 → https://rendmaster.com
[126/180] Ridgeons → https://www.ridgeons.co.uk
[127/180] Ridgeway → https://ridgeway-online.com
[128/180] Selco Trade Centres → https://www.selcobw.com
[129/180] SIG Construction Accessories → https://sigca.co.uk
[130/180] SAMAC Fixings → https://samacfixings.co.uk
[131/180] Sika Limited → https://gbr.sika.com
[132/180] SIMPSON STRONG-TIE → https://www.strongtie.co.uk
[133/180] SIG plc. → https://www.sigplc.com
[134/180] Saint-Gobain Weber Limited → https://www.uk.weber
[135/180] RSI Store LTD → https://renderingsuppliesireland.com
[136/180] Premier Render Supplies Ltd. → https://www.prsupplies.co.uk
[137/180] Sika Limited → https://gbr.sika.com
[138/180] RM Norman Ltd → (not found)
[139/180] SIG Insulation → https://www.siginsulation.co.uk
[140/180] SIG Sheffield Insulations → https://www.sigplc.com
[141/180] SKANDA (UK) LIMITED → (not found)
[142/180] QUINN building products → (not found)
[143/180] sak Wholesale Limited UK 138591 → (not found)
[144/180] SPS Envirowall Ltd → https://spsenvirowall.co.uk
[145/180] Smet Building Products → https://www.smetbuildingproducts.com
[146/180] SPS Envirowall Ltd. → https://spsenvirowall.co.uk
[147/180] SPS Envirowall Ltd. → https://spsenvirowall.co.uk
[148/180] Soltherm External Wall Insulation Wales Limited → (not found)
[149/180] Sabrefix → (not found)
[150/180] Specialist Render Supplies Ltd. (138551) → https://specialistrendersupplies.co.uk
[151/180] Superior Render Supplies → https://www.superiorrendersupplies.co.uk
[152/180] Superior Render Supplies  (138574) → https://www.superiorrendersupplies.co.uk
[153/180] SPS envirowall Ltd. → https://spsenvirowall.co.uk
[154/180] STRUCTHERM Ltd → https://www.structherm.co.uk
[155/180] Teco Building Products → https://tecoproducts.co.uk
[156/180] Sto Ltd. - in Liquidation → https://www.sto.co.uk
[157/180] SOLTHERM WALL INSULATION LTD → https://www.soltherm.co.uk
[158/180] The Render Depot → https://www.therenderdepot.co.uk
[159/180] SWIP Ltd. → https://www.swipiwi.co.uk
[160/180] SWM Insulations → https://www.swmbuildersmerchants.co.uk
[161/180] SIG Insulation → https://mcprod.sigdistribution.co.uk
[162/180] The Render Depot (138587) → https://www.therenderdepot.co.uk
[163/180] Travis Perkins Trading Co. Ltd → https://www.travisperkins.co.uk
[164/180] stanta UK Ltd. → https://www.stanta.com
[165/180] Walls & Ceilings International → https://www.walls-and-ceilings.co.uk
[166/180] The Facade Hub (138511) → https://www.thefacadeshub.co.uk
[167/180] UK Render Supply 138553 → https://ukrendersupply.com
[168/180] Trueline Expanded Products Ltd → https://www.truelineproducts.co.uk
[169/180] Specialst Construction → (not found)
[170/180] Wetherby Group → https://www.wetherbygroup.com
[171/180] Woodman Brothers → https://www.woodmanbrothers.co.uk
[172/180] Vista Engineering → https://www.vistaeng.co.uk
[173/180] Wolseley UK → https://www.wolseley.co.uk
[174/180] WPS Plastering Contractors Ltd → https://www.wpsplasteringcontractors.co.uk
[175/180] Vimark Render UK → https://www.vimark.co.uk
[176/180] Wetherby Building Systems Ltd. → https://www.wall-systems.co.uk
[177/180] Urban West Ltd. → (not found)
[178/180] Woods Insulation → (not found)
[179/180] U K Hardware Distribution → (not found)
[180/180] Tremco CPG UK Limited → https://www.cpg-europe.com

Done! Websites found: 148/180

                       Kundenname                                    Website
0     138395 F & T Terrix Limitid                  https://www.ft-terrix.com
1                Addagrip Surface                     https://addagrip.co.uk
2      AHL Architectural Hardware
3                        ALIVA UK                        https://alivauk.com
4                        ALIVA UK                        https://alivauk.com
5       Allmat (East Surrey) Ltd.  https://www.allmat-buildingsupplies.co.uk
6             alsecco (U.K.) Ltd.                      https://alsecco.co.uk
7              Amaroc -  gelöscht
8                     Baumit  Ltd                       https://baumit.co.uk
9            Belgrade Insulations        https://www.belgradeinsulations.com
10           Belgrade Insulations        https://www.belgradeinsulations.com
11  Belgrade Insulations (138552)        https://www.belgradeinsulations.com
12               Belmore Supplies             https://www.belmoretools.co.uk
13             Benchmark Building
14               Bluebuild Energy            https://www.bluebuildenergy.com
15                     Bostik Ltd                     https://www.bostik.com
16                      Bradfords                https://www.bradfords.co.uk
17            British Gypsum PLC.             https://www.british-gypsum.com
18                Bryson Products                   https://www.bryson.co.uk
19             BTS INTERIORS LTD.

In [11]:
df_enriched.head()

,Kundenname,Straße,Ort,PLZ,Land,Tätigkeit,Größe,Produktpalette,Website
0,138395 F & T Terrix Limitid,"Chichester Street, Unit 14 Chichester busines...",Rochdale,OL16 2AU,GB,"Fassaden-/Putzsysteme, Baustoffe",klein; <50 MA; 1 Standort,"Render, Putz/Spritzputz, Farben/Lacksysteme, K...",https://www.ft-terrix.com
1,Addagrip Surface,Bell Lane Industrial Estate,"Uckfield, East Sussex",TN22 1QL,GB,Resin surfacing systems manufacturer,"<50 employees, 1 UK site","resin-bound surfacing, resin-bonded surfacing,...",https://addagrip.co.uk
2,AHL Architectural Hardware,Boucher Place,BELFAST,BT12 6TA,GB,Architectural ironmongery supply,Single site; small business,"Schlösser, Zylinder, Schlüssel/Schließsysteme,...",
3,ALIVA UK,Arlington Business Park,"Theale, Berkshire",RG7 4TY,GB,"Fassadenlösungen, hinterlüftete Systeme","2 Standorte, KMU (<50)","ETICS/EWI, Rainscreen, Porzellan/Feinsteinzeug...",https://alivauk.com
4,ALIVA UK,"Oak Tree Barn, Unit 6",Warrington,WA4 4BX,GB,"Fassadensysteme, EWI, Rainscreen","HQ Süd, Büro/Showroom Nord","ETICS/EWI, Rainscreen-Cladding, Fassadenpaneel...",https://alivauk.com

In [12]:
df_enriched.to_excel("kunden_enriched_with_websites.xlsx", index=False)